# Generated by Django 2.0.4 on 2018-04-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordrelaygame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='wordrelaygame.Story'),
        ),
    ]
