language: python
python:
  - "3.6"
addons:
  postgresql: "9.6"
install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --deploy
before_script:
  - psql -c "create user cheddargorge with createdb password 'cheddargorge';" -U postgres
script:
  - cd cheddargorge
  - python manage.py test
