language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --deploy
before_script:
  - psql -c "create user cheddargorge with password 'cheddargorge';" -U postgres
  - psql -c "create database cheddargorge owner cheddargorge;" -U postgres
script:
  - python manage.py test
